### ISSUE TITLE
Uncaught Error: invalid putpolicy options

### ISSUE THREAD

**Issue by Meekdai** [Cubernet/insert-img#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [insert-img](https://github.com/Cubernet/insert-img) package 0.1.4

### Stack Trace

Uncaught Error: invalid putpolicy options

```
At C:\Users\Meekdai\.atom\packages\insert-img\node_modules\qiniu\qiniu\storage\rs.js:659

Error: invalid putpolicy options
    at /packages/insert-img/node_modules/qiniu/qiniu/storage/rs.js:659:11)
    at uptoken (/packages/insert-img/lib/paster.js:69:37)
    at /packages/insert-img/lib/paster.js:74:27
    at C:/Atom/resources/app/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -6:06.4.0 core:copy (input.hidden-input)
  6x -5:01.0 insert-img:paste (input.hidden-input)
     -3:55.1.0 script:run (input.hidden-input)
     -3:53.4.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -2:44.7.0 core:backspace (input.hidden-input)
     -2:29.4.0 script:close-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:55.8.0 insert-img:paste (input.hidden-input)
     -1:43.1.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-clock 0.1.7 
script 3.14.1 
auto-convert-to-utf8 0.1.0 
ex-mode 0.15.0 
insert-img 0.1.4 
markdown-pdf 1.5.0 
markdown-preview-enhanced 0.13.0 
minimap 4.28.2 
vim-mode 0.66.0 
```

**Comment by WangQiangrong** [comment]
同遇到这个问题，请问你解决了吗

**Comment by qwertylevel3** [comment]
https://github.com/qiniu/nodejs-sdk/issues/305
可以参考下这个
